apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: yuragranovsky/config-server
        resources:
          requests:
            memory: "150Mi"
            cpu: "500m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  type: ClusterIP  
  ports:
  - port: 8888
    targetPort: 8888
        
