apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits
spec:
  selector:
    matchLabels:
      app: visits
  replicas: 2
  template:
    metadata:
      labels:
        app: visits
    spec:
      containers:
      - name: visits
        image: yuragranovsky/visits
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 9292
---
apiVersion: v1
kind: Service
metadata:
  name: visits
spec:
  selector:
    app: visits
  ports:
  - port: 9292
    targetPort: 9292
