apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: yuragranovsky/gateway
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: CONFIG_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              key: configServer
              name: pm-config-map
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef





        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer  
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000

